config/routes.rb
Rails.application.routes.draw do

  resources :doctors 
  resources :professions do
    resources :doctors
  end

  root "doctors#index"
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	belongs_to :profession

	validates_presence_of :first_name, :last_name, :address_1, :city, :country, :zip_code

	geocoded_by :address
	after_validation :geocode  

	def address
		[self.address_1, self.address_2, self.zip_code, self.city, self.country].compact.join(", ")
	end

end

app/models/profession.rb
class Profession < ActiveRecord::Base
	has_many :doctors

	validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

	def index
		@doctors = Doctor.all
	end

	def new
		@doctor = Doctor.new
	end

	def create
		@doctor = Doctor.create(doctor_params)

		if @doctor.valid?
			redirect_to doctors_url
		else
			render :new
		end

	end



	private
	def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :address_1, :address_2, :city, :country, :zip_code, :profession_id)
    end
end

app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController
	def index
	end

	def new
		@profession = Profession.new
	end

	def create
		@profession = Profession.create(profession_params)

		if @profession.valid?
			redirect_to professions_url
		else
			render :new
		end
	end


	private
	def profession_params
      params.require(:profession).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doctors/_doctor.html.erb
<div style="border-radius: 5px; border: 1px solid #CCC; padding: 10px; margin: 10px;">
	<p style="font-weight: bold;"><%= doctor.first_name %> <%= doctor.last_name %></p>
	<p style="font-size: 24px;"><%= doctor.profession.name %></p>
	<%= doctor.address_1 %><br/>
	<%= doctor.address_2 %><br/>
	<%= doctor.zip_code %> <%= doctor.city%><br/>
	<%= doctor.country %>
</div>

app/views/doctors/_form.html.erb
<div style="width: 500px; border: 1px solid #CCC; margin: 20px auto; padding: 10px;">
	<%= simple_form_for @doctor do |f| %>
	  <%= f.association :profession %>
	  <%= f.input :first_name %>  
	  <%= f.input :last_name %>  
	  <%= f.input :address_1 %>  
	  <%= f.input :address_2 %>  
	  <%= f.input :zip_code %>  
	  <%= f.input :city %>  
	  <%= f.input :country %>  
	  <%= f.button :submit %>
	<% end %>
</div>

app/views/doctors/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


<br/><br/>

<%= link_to "Ajout un docteur", new_doctor_url, :class => "btn btn-primary btn-lg"%>

<br/><br/>

<script>
	var doctors = <%= raw @doctors.to_json %>;
</script>
<div style="width: 40%; display: inline-block; vertical-align: top;" >
	<%= render partial: "doctor", collection: @doctors %>
</div>

<div style="width: 40%; display: inline-block;  vertical-align: top;" >
  <div id="map-canvas" style='width: 500px; height: 400px;'></div>
</div>

<script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: { lng: 2.35, lat: 48.8475908},
          zoom: 12
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);

        for(i=0; i < doctors.length; i++)
        {
	        var myLatlng = new google.maps.LatLng(doctors[i].latitude, doctors[i].longitude);

	        var marker = new google.maps.Marker({
			      position: myLatlng,
			      map: map,
			      title: doctors[i].first_name + " " + doctors[i].last_name 
  			  });

	     }


    }
    google.maps.event.addDomListener(window, 'load', initialize);


</script>

app/views/doctors/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoctorWho</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCOLUG4HQ6x_PIOklIRd1ZGo2axPMCXwBI">
    </script>
</head>
<body>

<div class="page-header">
  <h1>Doctor Who</h1>
</div>

<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to "Docteurs", doctors_path %></li>
  <li role="presentation"><%= link_to "Professions", professions_path %></li>
</ul>

<%= yield %>


</body>
</html>

app/views/professions/_form.html.erb
<div style="width: 500px; border: 1px solid #CCC; margin: 20px auto; padding: 10px;">
	<%= simple_form_for @profession do |f| %>
	  <%= f.input :name %>  
	  <%= f.button :submit %>
	<% end %>
</div>

app/views/professions/index.html.erb
<br/><br/>

<%= link_to "Ajout une profession", new_profession_url, :class => "btn btn-primary btn-lg"%>

<br/><br/>

<ul>
	<% Profession.all.each do |profession| %>
		<li><%= profession.name %></li>
	<% end %>
</ul>

app/views/professions/new.html.erb
<%= render "form" %>